//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrolIndexer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Herstelbon
    {
        public int HerstelbonId { get; set; }
        public Nullable<System.DateTime> Aanmaakdatum { get; set; }
        public string Klachtomschrijving { get; set; }
        public string Computeromschrijving { get; set; }
        public string Accessoires { get; set; }
        public string Opmerkingen { get; set; }
        public Nullable<int> TechnicusId { get; set; }
        public int KlantId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Klant Klant { get; set; }
        public virtual Technicus Technicus { get; set; }
        public virtual Status Status { get; set; }
    }
}
