//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrolIndexer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HerstellingenEntities : DbContext
    {
        public HerstellingenEntities()
            : base("name=HerstellingenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Herstelbon> Herstelbonnen { get; set; }
        public DbSet<Klant> Klanten { get; set; }
        public DbSet<Technicus> Technici { get; set; }
        public DbSet<Status> Statussen { get; set; }
    }
}
