//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrolIndexer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klant
    {
        public Klant()
        {
            this.Herstelbonnen = new HashSet<Herstelbon>();
        }
    
        public int KlantId { get; set; }
        public string Voornaam { get; set; }
        public string Familienaam { get; set; }
        public string Straat { get; set; }
        public string HuisNr { get; set; }
        public string Postcode { get; set; }
        public string Woonplaats { get; set; }
        public string Telefoon { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<Herstelbon> Herstelbonnen { get; set; }
    }
}
