//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrolIndexer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technicus
    {
        public Technicus()
        {
            this.Herstelbonnen = new HashSet<Herstelbon>();
        }
    
        public int TechnicusId { get; set; }
        public string Voornaam { get; set; }
        public string Familienaam { get; set; }
        public string Specialiteit { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<Herstelbon> Herstelbonnen { get; set; }
    }
}
